services:
  frontend:
    image: todolist-frontend
    pull_policy: never
    container_name: todolist-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  mysql-database:
    image: mysql:8.0.40-bookworm
    container_name: todolist-mysql-database
    volumes:
      - todolist-mysql-data:/var/lib/mysql
    env_file:
      - ./Database/database.env
    ports:
      - 3306:3306

  backend:
    image: todolist-backend
    pull_policy: never
    container_name: todolist-backend
    build:
      context: ./Backend/backend-service
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080

volumes:
  todolist-mysql-data: