services:
  frontend:
    image: todolist-frontend
    pull_policy: never
    container_name: todolist-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 80:80