services:
  frontend:
    image: todolist-frontend
    pull_policy: never
    container_name: todolist-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - 80:80

  postgres-database:
    image: todolist-postgres-database
    pull_policy: never
    container_name: todolist-postgres-database
    build:
      context: ./Database
      dockerfile: Dockerfile
    volumes:
      - todolist-postgres-data:/var/lib/postgresql/data
    env_file:
      - ./Database/database.env
    ports:
      - 5432:5432

  backend:
    image: todolist-backend
    pull_policy: never
    container_name: todolist-backend
    build:
      context: ./Backend/backend-service
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - 8080:8080
    depends_on:
      - postgres-database

volumes:
  todolist-postgres-data: